### ISSUE TITLE
Explanation of API params

### ISSUE THREAD

**Issue by AlaaL** [amelaraby/magento-2-mageplaza-social-login-api#2]
Hello, 
Thanks for this great plugin, I just want to know what are the params $token, $tokenSecret, $refreshToken in this function

   ` public function createCustomerAccessToken($provider, $token, $tokenSecret = '', $refreshToken = '');`
And where do i get them ? I am developing a flutter app for Magento and also using Magepalza social login extension

**Comment by amelaraby** [comment]
Hello @AlaaL,

Here is the params list:

- `provider`: required - can be any of the providers mentioned [here](https://github.com/mageplaza/magento-2-social-login/blob/v4.1.9/Helper/Social.php#L268)
- `token`: required - this is the access token which you get on the client after a successful login with the provider such as facebook, google ... etc. 
  - for example: if you're using [this package](https://pub.dev/packages/flutter_facebook_login) for flutter, you should send the value from `result.accessToken.token` as mentioned [here](https://pub.dev/packages/flutter_facebook_login#how-do-i-use-it).
- `tokenSecret` and `refreshToken`: optional - you can get from the client library same as the access token as well.

Hope that helps!

**Comment by AlaaL** [comment]
Yes very helpful, thank you for your help.
